/*
 *  Copyright 2010 chris.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * DialogHeaderPanel2.java
 *
 * Created on 31-ene-2010, 12:06:53
 */

package org.gitools.ui.platform.dialog;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Icon;

public class DialogHeaderPanel extends javax.swing.JPanel {

	private static final Color INFO_COLOR = Color.WHITE;
	private static final Color WARN_COLOR = new Color(250, 250, 160);
	private static final Color ERROR_COLOR = new Color(250, 150, 150);
	private static final Color PROGRESS_COLOR = new Color(100, 180, 250);

	private MessageStatus status;

    public DialogHeaderPanel() {
        initComponents();

		title.setFont(title.getFont().deriveFont(Font.BOLD));
		message.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
		logo.setText("");

		status = MessageStatus.INFO;
    }

	public DialogHeaderPanel(
			String header,
			String message,
			MessageStatus status,
			Icon logo) {
		this();

		setHeader(header);
		setStatus(status);
		setMessage(message);
		setLogo(logo);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setFocusable(false);

        title.setText("Title");
        title.setFocusable(false);
        title.setRequestFocusEnabled(false);

        message.setBackground(java.awt.Color.white);
        message.setText("Message");
        message.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        message.setFocusable(false);
        message.setOpaque(true);
        message.setRequestFocusEnabled(false);
        message.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        logo.setText("Logo");
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        logo.setFocusable(false);
        logo.setRequestFocusEnabled(false);
        logo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(message)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logo;
    private javax.swing.JLabel message;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

	public String getHeader() {
		return title.getText();
	}

	public void setHeader(String title) {
		this.title.setText(title);
	}

	public String getMessage() {
		return message.getText();
	}

	public void setMessage(String message) {
		this.message.setText(message);
	}

	public MessageStatus getStatus() {
		return status;
	}

	public void setStatus(MessageStatus status) {
		this.status = status;
		//TODO status icon
		switch (status) {
			case INFO: message.setBackground(INFO_COLOR); break;
			case WARN: message.setBackground(WARN_COLOR); break;
			case ERROR: message.setBackground(ERROR_COLOR); break;
			case PROGRESS: message.setBackground(PROGRESS_COLOR); break;
		}
	}

	public Icon getLogo() {
		return logo.getIcon();
	}

	public void setLogo(Icon logo) {
		this.logo.setIcon(logo);
	}
}
