/*
 * ModuleFilteringPanel.java
 *
 * Created on September 3, 2009, 6:30 PM
 */

package org.gitools.ui.wizard.analysis;

/**
 *
 * @author  cperez
 */
public class ModuleFilteringPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -3938595143114651781L;
	
	/** Creates new form ModuleFilteringPanel */
    public ModuleFilteringPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minSizeEnableChk = new javax.swing.JCheckBox();
        minSizeValueCbox = new javax.swing.JComboBox();

        minSizeEnableChk.setSelected(true);
        minSizeEnableChk.setText("Omit modules having less rows than");
        minSizeEnableChk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                minSizeEnableChkItemStateChanged(evt);
            }
        });

        minSizeValueCbox.setEditable(true);
        minSizeValueCbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "20", "30", "50", "100" }));
        minSizeValueCbox.setSelectedIndex(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minSizeEnableChk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minSizeValueCbox, 0, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minSizeValueCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minSizeEnableChk))
                .addContainerGap(255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void minSizeEnableChkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_minSizeEnableChkItemStateChanged
    minSizeValueCbox.setEnabled(minSizeEnableChk.isSelected());
}//GEN-LAST:event_minSizeEnableChkItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox minSizeEnableChk;
    public javax.swing.JComboBox minSizeValueCbox;
    // End of variables declaration//GEN-END:variables

}
