#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
BINDIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$BINDIR/$SOURCE"
  BINDIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
BINDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source $BINDIR/common.sh

$javacmd -jar $LIBDIR/org.gitools.cli-${project.version}.jar oncodrive $*
