/*
 *  Copyright 2011 chris.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * ColoredClustersConfigPage.java
 *
 * Created on 02-mar-2011, 8:27:23
 */

package org.gitools.ui.heatmap.header.coloredlabels;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.gitools.heatmap.header.HeatmapColoredLabelsHeader;
import org.gitools.ui.platform.dialog.FontChooserDialog;
import org.gitools.ui.platform.wizard.AbstractWizardPage;
import org.gitools.ui.utils.FontUtils;

public class ColoredLabelsConfigPage extends AbstractWizardPage {

	private HeatmapColoredLabelsHeader header;

	private Font labelFont;

	public ColoredLabelsConfigPage() {
		this(new HeatmapColoredLabelsHeader(null));
	}

    /** Creates new form ColoredClustersConfigPage */
    public ColoredLabelsConfigPage(HeatmapColoredLabelsHeader header) {
		super();

		this.header = header;

        initComponents();

		labelVisibleChk.addChangeListener(new ChangeListener() {
			@Override public void stateChanged(ChangeEvent e) {
				labelVisibleChanged(); }
		});

		labelFontBtn.addActionListener(new ActionListener() {
			@Override public void actionPerformed(ActionEvent e) {
				selectFont(); }
		});

		setTitle("Header configuration");
		setComplete(true);
    }

	@Override
	public void updateControls() {
		super.updateControls();

		titleField.setText(header.getTitle());
		thicknessSpin.setValue(header.getThickness());
		marginSpin.setValue(header.getMargin());
		separationGridChk.setSelected(header.isSeparationGrid());

		labelVisibleChk.setSelected(header.isLabelVisible());
		labelFont = header.getLabelFont();
		fontChanged();
		labelRotatedChk.setSelected(header.isLabelRotated());
		labelColorDefinedChk.setSelected(header.isLabelColorDefined());
		labelColor.setColor(header.getLabelColor());
		labelVisibleChanged();
	}

	private void labelVisibleChanged() {
		boolean e = labelVisibleChk.isSelected();
		labelFontField.setEnabled(e);
		labelFontBtn.setEnabled(e);
		labelRotatedChk.setEnabled(e);
		labelColorDefinedChk.setEnabled(e);
		labelColor.setEnabled(labelColorDefinedChk.isSelected() && e);
	}

	private void fontChanged() {
		labelFontField.setText(FontUtils.fontText(labelFont));
		labelFontField.setFont(labelFont);
	}

	private void selectFont() {
		FontChooserDialog dlg =
				new FontChooserDialog(null, header.getLabelFont());
		dlg.setVisible(true);

		if (dlg.isCancelled())
			return;

		labelFont = dlg.getFont();
		fontChanged();
	}

	@Override
	public void updateModel() {
		super.updateModel();

		header.setTitle(titleField.getText());
		header.setThickness((Integer) thicknessSpin.getValue());
		header.setMargin((Integer) marginSpin.getValue());
		header.setSeparationGrid(separationGridChk.isSelected());
		header.setLabelVisible(labelVisibleChk.isSelected());
		header.setLabelFont(labelFont);
		header.setLabelRotated(labelRotatedChk.isSelected());
		header.setLabelColorDefined(labelColorDefinedChk.isSelected());
		header.setLabelColor(labelColor.getColor());
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        labelVisibleChk = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        labelFontField = new javax.swing.JTextField();
        labelFontBtn = new javax.swing.JButton();
        labelRotatedChk = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        thicknessSpin = new javax.swing.JSpinner();
        separationGridChk = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        marginSpin = new javax.swing.JSpinner();
        labelColor = new org.gitools.ui.platform.component.ColorChooserLabel();
        labelColorDefinedChk = new javax.swing.JCheckBox();

        jLabel1.setText("Title");

        labelVisibleChk.setText("Show cluster names");
        labelVisibleChk.setEnabled(false);

        jLabel2.setText("Font");

        labelFontField.setEditable(false);

        labelFontBtn.setText("...");

        labelRotatedChk.setText("Rotated text");

        jLabel4.setText("Thickness");
        jLabel4.setEnabled(false);

        thicknessSpin.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(14), Integer.valueOf(0), null, Integer.valueOf(1)));
        thicknessSpin.setEnabled(false);

        separationGridChk.setText("Grid between different clusters");

        jLabel3.setText("Margin");

        marginSpin.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        labelColor.setColor(new java.awt.Color(1, 1, 1));
        labelColor.setPreferredSize(new java.awt.Dimension(28, 28));

        labelColorDefinedChk.setText("All cluster names with the same color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleField, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marginSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thicknessSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(separationGridChk)
                            .addComponent(labelVisibleChk)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRotatedChk)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFontField, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFontBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelColorDefinedChk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(marginSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(thicknessSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separationGridChk)
                .addGap(18, 18, 18)
                .addComponent(labelVisibleChk)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelFontField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFontBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(labelRotatedChk)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColorDefinedChk)
                    .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup colorGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.gitools.ui.platform.component.ColorChooserLabel labelColor;
    private javax.swing.JCheckBox labelColorDefinedChk;
    private javax.swing.JButton labelFontBtn;
    private javax.swing.JTextField labelFontField;
    private javax.swing.JCheckBox labelRotatedChk;
    private javax.swing.JCheckBox labelVisibleChk;
    private javax.swing.JSpinner marginSpin;
    private javax.swing.JCheckBox separationGridChk;
    private javax.swing.JSpinner thicknessSpin;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables


	public HeatmapColoredLabelsHeader getHeader() {
		return header;
	}

	public void setHeader(HeatmapColoredLabelsHeader header) {
		this.header = header;
	}
}
