/*
 *  Copyright 2009 chris.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * BiomartAttributeDialog.java
 *
 * Created on 18-dic-2009, 22:11:43
 */

package org.gitools.ui.biomart.dialog;

import java.util.List;
import org.gitools.biomart.soap.model.AttributeInfo;
import org.gitools.biomart.soap.model.AttributePage;
import org.gitools.biomart.soap.model.DatasetInfo;
import org.gitools.biomart.soap.model.Mart;
import org.gitools.biomart.soap.model.MartServiceSoap;

import org.gitools.ui.biomart.panel.BiomartAttributePanel.AttributeSelectionListener;

public class BiomartAttributeDialog extends javax.swing.JDialog {

	boolean cancelled;

	public BiomartAttributeDialog(
			java.awt.Frame parent, List<AttributePage> attrPages) {

		super(parent, true);

        initComponents();

		setTitle("Select attributes");

		updateButtons();

		biomartAttrPanel.addAttributeSelectionListener(new AttributeSelectionListener() {
			@Override public void selectionChanged() {
				updateButtons(); }
		});

		cancelled = false;

		biomartAttrPanel.setAttributePages(attrPages);
	}
	
	public void open() {
		setVisible(true);
	}

	public boolean isCancelled() {
		return cancelled;
	}

	public List<AttributeInfo> getSelectedAttributes() {
		return biomartAttrPanel.getSelectedAttributes();
	}

	public List<String> getSelectedAttributeNames() {
		return biomartAttrPanel.getSelectedAttributeNames();
	}

	protected void updateButtons() {
		acceptBtn.setEnabled(
				biomartAttrPanel.getSelectedAttributes().size() > 0);
	}

	public void setBiomartParameters(
			MartServiceSoap port,
			Mart mart,
			DatasetInfo dataset) {
		
		biomartAttrPanel.setBiomartParameters(port, mart, dataset);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biomartAttrPanel = new org.gitools.ui.biomart.panel.BiomartAttributePanel();
        cancelBtn = new javax.swing.JButton();
        acceptBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(acceptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(biomartAttrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(biomartAttrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(acceptBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
		setVisible(false);
	}//GEN-LAST:event_acceptBtnActionPerformed

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
		cancelled = true;
		setVisible(false);
	}//GEN-LAST:event_cancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private org.gitools.ui.biomart.panel.BiomartAttributePanel biomartAttrPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
