/*
 *  Copyright 2010 Universitat Pompeu Fabra.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * ExamplePage.java
 *
 * Created on Oct 13, 2010, 1:37:37 PM
 */

package org.gitools.ui.analysis.wizard;

import java.awt.BorderLayout;
import java.net.URL;
import org.apache.velocity.VelocityContext;
import org.gitools.ui.platform.panel.TemplatePanel;
import org.gitools.ui.platform.wizard.AbstractWizardPage;

public class ExamplePage extends AbstractWizardPage {

    public ExamplePage(String title) {
        initComponents();

		URL url = getClass().getResource("/vm/new_analysis_intro.vm");
		try {
			VelocityContext context = new VelocityContext();
			context.put("analysis_title", title);
			TemplatePanel panel = new TemplatePanel();
			panel.setTemplateFromResource("/vm/new_analysis_intro.vm", url);
			panel.render(context);
			textPanel.setLayout(new BorderLayout());
			textPanel.add(panel, BorderLayout.CENTER);
		}
		catch (Exception ex) {
		}
		
		setComplete(true);
    }

	public boolean isExampleEnabled() {
		return exampleCheck.isSelected();
	}

	public boolean isShowAgain() {
		return !dontShowAgainCheck.isSelected();
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPanel = new javax.swing.JPanel();
        exampleCheck = new javax.swing.JCheckBox();
        dontShowAgainCheck = new javax.swing.JCheckBox();

        textPanel.setBackground(new java.awt.Color(254, 254, 254));
        textPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        exampleCheck.setText("Fill this wizard with an example");

        dontShowAgainCheck.setText("Don't show this page next time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dontShowAgainCheck)
                    .addComponent(exampleCheck))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exampleCheck)
                .addGap(18, 18, 18)
                .addComponent(dontShowAgainCheck)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dontShowAgainCheck;
    private javax.swing.JCheckBox exampleCheck;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables

}
