#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
BINDIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$BINDIR/$SOURCE"
  BINDIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
BINDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source $BINDIR/common.sh

echo This command is not implemented yet, sorry.

exit -1

$javacmd -jar $LIBDIR/gitools-cli-${project.version}.jar matrix-filter $*
