/*
 *  Copyright 2011 Universitat Pompeu Fabra.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * ExportHeatmapLabelsPage.java
 *
 * Created on 23-mar-2011, 9:22:07
 */

package org.gitools.ui.wizard.common;

import org.gitools.ui.platform.wizard.AbstractWizardPage;

public class ExportHeatmapLabelsPage extends AbstractWizardPage {

	public enum WhichLabels {
		VISIBLE_ROWS, VISIBLE_COLUMNS,
		HIDDEN_ROWS, HIDDEN_COLUMNS
	}

	public ExportHeatmapLabelsPage() {
        initComponents();

		setTitle("What do you want to export ?");
		setComplete(true);
    }

	public WhichLabels getWhichLabels() {
		if (vRowsRb.isSelected())
			return WhichLabels.VISIBLE_ROWS;
		if (vColsRb.isSelected())
			return WhichLabels.VISIBLE_COLUMNS;
		if (hRowsRb.isSelected())
			return WhichLabels.HIDDEN_ROWS;
		if (hColsRb.isSelected())
			return WhichLabels.HIDDEN_COLUMNS;
		return WhichLabels.VISIBLE_ROWS;
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        vRowsRb = new javax.swing.JRadioButton();
        vColsRb = new javax.swing.JRadioButton();
        hRowsRb = new javax.swing.JRadioButton();
        hColsRb = new javax.swing.JRadioButton();

        buttonGroup1.add(vRowsRb);
        vRowsRb.setSelected(true);
        vRowsRb.setText("Visible rows");

        buttonGroup1.add(vColsRb);
        vColsRb.setText("Visible columns");

        buttonGroup1.add(hRowsRb);
        hRowsRb.setText("Hidden rows");

        buttonGroup1.add(hColsRb);
        hColsRb.setText("Hidden columns");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vRowsRb)
                    .addComponent(vColsRb)
                    .addComponent(hRowsRb)
                    .addComponent(hColsRb))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vRowsRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vColsRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hRowsRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hColsRb)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton hColsRb;
    private javax.swing.JRadioButton hRowsRb;
    private javax.swing.JRadioButton vColsRb;
    private javax.swing.JRadioButton vRowsRb;
    // End of variables declaration//GEN-END:variables

}
