/*
 *  Copyright 2010 xrafael.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */


package org.gitools.ui.analysis.clustering.dialog;

public class CobwebParamsPanel extends javax.swing.JPanel {

    /** Creates new form cobwebParamsPanel */
    public CobwebParamsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        acuityField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cutOffField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        seedField = new javax.swing.JTextField();
        acuityCombo = new javax.swing.JComboBox();
        cutOffCombo = new javax.swing.JComboBox();
        seedCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Acuity : ");

        acuityField.setText("1.0");
        acuityField.setEnabled(false);

        jLabel2.setText("Cutoff : ");

        cutOffField.setText("0.0028");
        cutOffField.setEnabled(false);

        jLabel3.setText("Seed : ");

        seedField.setText("42");
        seedField.setEnabled(false);

        acuityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "specify" }));
        acuityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acuityComboActionPerformed(evt);
            }
        });

        cutOffCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "specify" }));
        cutOffCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutOffComboActionPerformed(evt);
            }
        });

        seedCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "default", "specify" }));
        seedCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedComboActionPerformed(evt);
            }
        });

        jLabel4.setText("value :");

        jLabel5.setText("value :");

        jLabel6.setText("value :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(seedCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cutOffCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acuityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seedField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(cutOffField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(acuityField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(cutOffField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(acuityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acuityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cutOffCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(seedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void acuityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acuityComboActionPerformed

		if (acuityCombo.getSelectedItem().toString().toLowerCase().equals("specify"))
			acuityField.setEnabled(true);
		else
			acuityField.setEnabled(false);
	}//GEN-LAST:event_acuityComboActionPerformed

	private void cutOffComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutOffComboActionPerformed
		if (cutOffCombo.getSelectedItem().toString().toLowerCase().equals("specify"))
			cutOffField.setEnabled(true);
		else
			cutOffField.setEnabled(false);
	}//GEN-LAST:event_cutOffComboActionPerformed

	private void seedComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedComboActionPerformed

		if (seedCombo.getSelectedItem().toString().toLowerCase().equals("specify"))
			seedField.setEnabled(true);
		else
			seedField.setEnabled(false);
	}//GEN-LAST:event_seedComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox acuityCombo;
    private javax.swing.JTextField acuityField;
    private javax.swing.JComboBox cutOffCombo;
    private javax.swing.JTextField cutOffField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox seedCombo;
    private javax.swing.JTextField seedField;
    // End of variables declaration//GEN-END:variables

	//FIXME: specify high,mid,low values for cutOff
	public String getCutoff(){
		if (cutOffCombo.getSelectedItem().toString().equals("default"))
			return "0.0028";
		else
			if (cutOffCombo.getSelectedItem().toString().equals("specify"))
				return cutOffField.getText();
			else
				return "0.0028";
	}

	//FIXME: specify high,mid,low values for Acuity
	public String getAcuity(){
		if (acuityCombo.getSelectedItem().toString().equals("default"))
			return "1.0";
		else
			if (acuityCombo.getSelectedItem().toString().equals("specify"))
				return acuityField.getText();
			else
				return "1.0";
	}

	//FIXME: specify high,mid,low values for Seed
	public String getSeed(){
		if (seedCombo.getSelectedItem().toString().equals("default"))
			return "42";
		else
			if (seedCombo.getSelectedItem().toString().equals("specify"))
				return seedField.getText();
			else
				return "42";
	}

}
